name: mars
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - dgl-cuda11.3
  - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
  - tqdm
  - tensorboard
  - scikit-learn=0.23.2
  - rdkit=2021.03.5
  - psutil
